org.gradle.jvmargs=-Xmx1200m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.parallel=false
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.workers.max=1
org.gradle.vfs.watch=false
kotlin.compiler.execution.strategy=in-process
googleServices.missing.passthrough=true
